version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2

    environment:
      PROJECT_PATH: "~/project"  # Set the project path (quoting for potential special characters)

    steps:
      - checkout  # Checkout the source code from the repository

      - run: php --version && composer --version  # Display PHP and Composer versions

      - run: composer --global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true  # Configure Composer for PHP CodeSniffer

      - run: cd .circleci && composer require drupal/coder -vvv  # Install Drupal Coder using Composer

      - run:
          name: "Configure Drupal Coding Standards"
          command: |
            ./.circleci/vendor/bin/phpcs --ignore=./.circleci/* --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,yml,md $PROJECT_PATH
          # Run PHP CodeSniffer with Drupal coding standards on the specified project path

workflows:
  version: 2
  drupalStandardsWorkflow:  # Define the workflow
    jobs:
      - build  # Include the 'build' job in the workflow
